export const GET_PRODUCT='GET_PRODUCT';


export const ADD_DEMAND="ADD_DEMAND"
export const UPDATE_DEMAND="UPDATE_DEMAND"
export const DELETE_DEMAND="DELETE_DEMAND"
export const CLEAR_DEMAND="CLEAR_DEMAND"
export const GET_DEMAND="GET_DEMAND"
export const REMOVE_CURRENT_DEMAND="REMOVE_CURRENT_DEMAND"
export const DEMAND_ERROR="DEMAND_ERROR"

// AUTH ACTIONS
export const REGISTER_SUCCESS="REGISTER_SUCCESS"
export const REGISTER_FAIL="REGISTER_FAIL"
export const LOGIN_SUCCESS="LOGIN_SUCCESS"
export const LOGIN_FAIL="LOGIN_FAIL"
export const AUTH_ERROR="AUTH_ERROR"
export const CLEAR_ERROR="CLEAR_ERROR"
export const LOGOUT = "LOGOUT"
export const USER_LOADED = "USER_LOADED"

// Alert Actions
export const SET_ALERT = "SET_ALERT"
export const REMOVE_ALERT = "REMOVE_ALERT"
